/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.ComponentOrientation;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.Box;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author Vu Xuan Thanh
 */
public class frmNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmNhanVien() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlbLuaChon = new javax.swing.JToolBar();
        pnlLuaChon = new javax.swing.JPanel();
        btnQuanLy = new javax.swing.JButton();
        btnBCTK = new javax.swing.JButton();
        btnThongTinTK = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        pnlHienThi = new javax.swing.JPanel();
        mnbTieuDe = new javax.swing.JMenuBar();
        mnuChucNang = new javax.swing.JMenu();
        mnuQuanLy = new javax.swing.JMenu();
        mniQLDanhMuc = new javax.swing.JMenuItem();
        mniQLDoAnNhanh = new javax.swing.JMenuItem();
        mniQLHoaDon = new javax.swing.JMenuItem();
        mniBCTK = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        mnuCaiDat = new javax.swing.JMenu();
        mniThongTinTK = new javax.swing.JMenuItem();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mnuThoat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lí đồ ăn nhanh");

        tlbLuaChon.setRollover(true);

        pnlLuaChon.setLayout(new java.awt.GridLayout());

        btnQuanLy.setText("Quản lý");
        btnQuanLy.setFocusable(false);
        btnQuanLy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlLuaChon.add(btnQuanLy);

        btnBCTK.setText("Đặt đồ ăn");
        btnBCTK.setFocusable(false);
        btnBCTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBCTK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlLuaChon.add(btnBCTK);

        btnThongTinTK.setText("Thông tin tài khoản");
        pnlLuaChon.add(btnThongTinTK);

        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.setFocusable(false);
        btnDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlLuaChon.add(btnDoiMatKhau);

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlLuaChon.add(btnDangXuat);

        btnThoat.setText("Thoát");
        btnThoat.setFocusable(false);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlLuaChon.add(btnThoat);

        tlbLuaChon.add(pnlLuaChon);

        javax.swing.GroupLayout pnlHienThiLayout = new javax.swing.GroupLayout(pnlHienThi);
        pnlHienThi.setLayout(pnlHienThiLayout);
        pnlHienThiLayout.setHorizontalGroup(
            pnlHienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        pnlHienThiLayout.setVerticalGroup(
            pnlHienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        mnuChucNang.setText("Chức năng");

        mnuQuanLy.setText("Quản lý");

        mniQLDanhMuc.setText("Danh mục");
        mnuQuanLy.add(mniQLDanhMuc);

        mniQLDoAnNhanh.setText("Đồ ăn nhanh");
        mnuQuanLy.add(mniQLDoAnNhanh);

        mniQLHoaDon.setText("Hóa đơn");
        mnuQuanLy.add(mniQLHoaDon);

        mnuChucNang.add(mnuQuanLy);

        mniBCTK.setText("Đặt đồ ăn");
        mnuChucNang.add(mniBCTK);

        mniDangXuat.setText("Đăng xuất");
        mnuChucNang.add(mniDangXuat);

        mnbTieuDe.add(mnuChucNang);

        mnuCaiDat.setText("Cài đặt");

        mniThongTinTK.setText("Thông tin tài khoản");
        mnuCaiDat.add(mniThongTinTK);

        mniDoiMatKhau.setText("Đổi mật khẩu");
        mnuCaiDat.add(mniDoiMatKhau);

        mnbTieuDe.add(mnuCaiDat);

        mnuThoat.setText("Thoát");
        mnbTieuDe.add(mnuThoat);

        setJMenuBar(mnbTieuDe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tlbLuaChon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tlbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Phần mềm quản lí đồ ăn nhanh-căng tin số 2_HaUI");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBCTK;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnQuanLy;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongTinTK;
    private javax.swing.JMenuBar mnbTieuDe;
    private javax.swing.JMenuItem mniBCTK;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniQLDanhMuc;
    private javax.swing.JMenuItem mniQLDoAnNhanh;
    private javax.swing.JMenuItem mniQLHoaDon;
    private javax.swing.JMenuItem mniThongTinTK;
    private javax.swing.JMenu mnuCaiDat;
    private javax.swing.JMenu mnuChucNang;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThoat;
    private javax.swing.JPanel pnlHienThi;
    private javax.swing.JPanel pnlLuaChon;
    private javax.swing.JToolBar tlbLuaChon;
    // End of variables declaration//GEN-END:variables
}
