/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL;
import DTO.ChiTietPhieuNhap;
import DTO.CustomTable_ChiTietPhieuNhap;
import DTO.CustomTable_PhieuNhap;
import DTO.PhieuNhap;
import java.awt.Frame;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vu Xuan Thanh
 */
public class frmQLPhieuNhap extends javax.swing.JFrame {

    /**
     * Creates new form frmQLPhieuNhap
     */
    BLL bll = new BLL();
    ArrayList<String> listNguyenLieu = new ArrayList<>();
    ArrayList<PhieuNhap> listPhieuNhap = new ArrayList<>();
    ArrayList<ChiTietPhieuNhap> listCTPN = new ArrayList<>();

    public frmQLPhieuNhap() {
        initComponents();
        loadTenNguyenLieu();
        loadTenNhaCC();
        loadTable();
        resetText();
        txtSoPhieu.setEnabled(false);
        txtNgayNhap.setEnabled(false);
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
        txtMaNguyenLieu.setEnabled(false);
        txtGiaNhap.setEnabled(false);
        spnSoLuong.setEnabled(false);
        lstNguyenLieu.setEnabled(false);
    }

    public void loadTable() {
      //  listCTPN = bll.getDataChiTietPhieuNhap();
    }

    public void loadTenNguyenLieu() {

//        try {
//            listNguyenLieu = bll.showTenNguyenLieu();
//        } catch (SQLException ex) {
//            Logger.getLogger(frmQLPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        DefaultListModel<String> model = new DefaultListModel<>();
//        for (String string : listNguyenLieu) {
//            model.addElement(string);
//        }
//        lstNguyenLieu.setModel(model);
    }

    public void resetText() {
        txtSoPhieu.setText("");
        txtGiaNhap.setText("");
        txtNgayNhap.setText("");
        txtMaNguyenLieu.setText("");
    }

    public void loadTenNhaCC() {
//        ArrayList<String> dsNCC = new ArrayList<>();
//
//        try {
//            dsNCC = bll.showTenNCC();
//        } catch (SQLException ex) {
//            Logger.getLogger(frmQLPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        for (String string : dsNCC) {
//            cbxNhaCungCap.addItem(string);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxNhaCungCap = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSoPhieu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaNguyenLieu = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNguyenLieu = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTietPhieuNhap = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnTao = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("QUẢN LÍ PHIẾU NHẬP NGUYÊN LIỆU");
        jPanel1.add(jLabel1);

        jLabel2.setText("Nhà cung cấp:");

        jLabel3.setText("Số phiếu");

        txtSoPhieu.setText("jTextField1");

        jLabel4.setText("Ngày nhập");

        txtNgayNhap.setText("jTextField1");

        jLabel5.setText("Nguyên liệu");

        txtMaNguyenLieu.setText("jTextField1");

        txtGiaNhap.setText("jTextField1");

        jLabel6.setText("Giá nhập");

        jLabel7.setText("Số lượng nhập:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxNhaCungCap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoPhieu)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addComponent(txtMaNguyenLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        lstNguyenLieu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNguyenLieuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstNguyenLieu);

        jLabel8.setText("DANH SÁCH NGUYÊN LIỆU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblChiTietPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChiTietPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblChiTietPhieuNhap);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );

        btnTao.setText("Tạo");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnTao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTao, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblChiTietPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietPhieuNhapMouseClicked
        // TODO add your handling code here:
        int row = tblChiTietPhieuNhap.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn 1 thông tin phiếu nhập cần xóa");
            return;
        }
        ChiTietPhieuNhap phieu = new ChiTietPhieuNhap();
        phieu = listCTPN.get(row);
        txtSoPhieu.setEnabled(true);
        txtMaNguyenLieu.setEnabled(true);
        txtGiaNhap.setEnabled(true);
        spnSoLuong.setEnabled(true);
        txtSoPhieu.setText(phieu.getSoPhieu());
        txtMaNguyenLieu.setText(phieu.getMaNL());
        txtGiaNhap.setText(phieu.getdGNhap() + "");
        spnSoLuong.setValue(phieu.getsLNhap());
    }//GEN-LAST:event_tblChiTietPhieuNhapMouseClicked

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            resetText();
//            txtSoPhieu.setText("PH" + RandomString.getAlphaNumericString(18));
//            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//            LocalDateTime now = LocalDateTime.now();
//            txtNgayNhap.setText(dtf.format(now));
//            int maNCC;
//
//            maNCC = bll.showMaCCTheoTen(cbxNhaCungCap.getSelectedItem().toString());
//
//            int t = bll.insertPhieuNhap(txtSoPhieu.getText(), txtNgayNhap.getText(), maNCC);
//
//            txtSoPhieu.setEnabled(true);
//            txtNgayNhap.setEnabled(true);
//            txtSoPhieu.setEditable(false);
//            txtNgayNhap.setEditable(false);
//            btnThem.setEnabled(true);
//            btnXoa.setEnabled(true);
//            txtMaNguyenLieu.setEnabled(true);
//            txtGiaNhap.setEnabled(true);
//            spnSoLuong.setEnabled(true);
//            lstNguyenLieu.setEnabled(true);
//            txtMaNguyenLieu.setEditable(false);
//            JOptionPane.showMessageDialog(null, "Đã thêm thành công 1 phiếu nhập " + txtSoPhieu.getText() + " "
//                    + txtNgayNhap.getText());
//
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi truy vấn " + ex.getMessage());
//
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi " + ex.getMessage());
//        }
    }//GEN-LAST:event_btnTaoActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
//        String soPhieu = txtSoPhieu.getText();
//        String ngayNhap = txtNgayNhap.getText();
//        if (soPhieu.isEmpty() || ngayNhap.isEmpty() || txtGiaNhap.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
//            return;
//        }
//        if (txtMaNguyenLieu.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Hãy chọn 1 nguyên liệu tương ứng");
//            return;
//        }
//        double giaNhap = 0;
//        try {
//            giaNhap = Double.parseDouble(txtGiaNhap.getText());
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi nhập sai kiểu số " + ex.getMessage());
//            return;
//        }
//        if (giaNhap < 0) {
//            JOptionPane.showMessageDialog(null, "Giá nhập phải lớn hơn 0");
//            return;
//        }
//        int soLuong = Integer.parseInt(spnSoLuong.getValue().toString());
//        if (soLuong <= 0) {
//            JOptionPane.showMessageDialog(null, "Số lượng phải lớn hơn 0");
//            return;
//        }
//        ChiTietPhieuNhap ctpn = new ChiTietPhieuNhap(soPhieu, txtMaNguyenLieu.getText());
//        if (listCTPN.contains(ctpn)) {
//            JOptionPane.showMessageDialog(null, "Phiếu nhập đã chứa thông tin của nguyên liệu này");
//            return;
//        }
//        try {
//            // TODO add your handling code here:
//            int t = bll.insertChiTietPhieuNhap(soPhieu, txtMaNguyenLieu.getText(), soLuong, giaNhap);
//            txtMaNguyenLieu.setText("");
//            txtGiaNhap.setText("");
//
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi truy vấn CSDL " + ex.getMessage());
//        } catch (Exception ex) {
//            Logger.getLogger(frmQLPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
//        if (txtSoPhieu.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Hãy chọn 1 thông tin phiếu nhập để xóa");
//            return;
//        }
//        try {
//            int t = bll.deleteChiTietPhieuNhap(txtSoPhieu.getText(), txtMaNguyenLieu.getText());
//
//            resetText();
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi truy vấn" + ex.getMessage());
//        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            int maNCC = bll.showMaCCTheoTen(cbxNhaCungCap.getSelectedItem().toString());
//            listPhieuNhap = bll.showPhieuNhapTheoMaNCC(maNCC);
//            tblChiTietPhieuNhap.setModel(new CustomTable_PhieuNhap(listPhieuNhap));
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi truy vấn " + ex.getMessage());
//        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void lstNguyenLieuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNguyenLieuValueChanged
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            String maML = bll.showMaNLTheoTen(lstNguyenLieu.getSelectedValue().toString());
//            txtMaNguyenLieu.setText(maML);
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi " + ex.getMessage());
//        }
    }//GEN-LAST:event_lstNguyenLieuValueChanged

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTao;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxNhaCungCap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstNguyenLieu;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTable tblChiTietPhieuNhap;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaNguyenLieu;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSoPhieu;
    // End of variables declaration//GEN-END:variables

}
